### ISSUE TITLE
Issue after installation

### ISSUE THREAD

**Issue by patrickcgray** [DigitalGlobe/geoio#13]
Hello!

I'mg getting an issue as soon as I try to import geoio. Is this built to work with Python 3.x or just 2.7?

```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geoio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/clifgray/anaconda3/envs/satimg/lib/python3.6/site-packages/geoio/__init__.py", line 5, in <module>
    from base import GeoImage
ModuleNotFoundError: No module named 'base'

```

**Comment by longbotham** [comment]
version 1.3.0 should work with python 3.  It is pushed to pypi so pip should work.  I'll plan to push the code to https://github.com/longbotham/geoio/ soon.

**Comment by patrickcgray** [comment]
Okay brilliant, please notify on here once you've pushed if you remember!
